# Generated by Django 4.2 on 2023-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule', models.CharField(max_length=25, unique=True)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('Sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=50)),
                ('Date_naiss', models.DateField(verbose_name='Date de naissance')),
                ('Lieu_naiss', models.CharField(max_length=50, verbose_name='Lieu de naissance')),
                ('Quartier', models.CharField(max_length=50)),
                ('Photo', models.ImageField(upload_to='image_eleves')),
                ('Nom_parent', models.CharField(max_length=50, verbose_name='Non du parents / Tuteur')),
                ('Telephone', models.CharField(max_length=9, verbose_name='Téléphone')),
            ],
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'managed': True, 'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterField(
            model_name='salledeclasse',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code de la salle de classe'),
        ),
        migrations.AlterField(
            model_name='salledeclasse',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom de la salle de classe'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Session active'),
        ),
        migrations.AlterModelTable(
            name='niveau',
            table='',
        ),
    ]
