# Generated by Django 4.2 on 2023-05-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_etudiant_alter_niveau_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='image_eleves'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='Prenom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom'),
        ),
        migrations.CreateModel(
            name='ClasseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salledeclasse')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session')),
            ],
        ),
    ]
