# Generated by Django 4.2 on 2023-05-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_etudiant_classe'),
        ('comptabilite', '0003_echeancepaiement_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('date_paiement', models.DateField(auto_now_add=True, verbose_name='date de paiement')),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.echeancepaiement')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etudiant')),
            ],
        ),
    ]
