# Generated by Django 4.2 on 2023-05-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_etudiant_classe'),
        ('comptabilite', '0004_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Payment',
        ),
    ]
